In [1]:
import numpy as np
import pandas as pd

In [114]:
X = np.array(
    [
        -7.207066,
        -5.722571,
        -4.915559,
        -8.345698,
        -5.570875,
        -5.493944,
        -6.574740,
        -6.546632,
        -6.564452,
        -6.890038,
        -6.477193,
        -6.998386,
        -6.776254,
        -5.935541,
        -5.040506,
        0.000000,
        5.889715,
        5.488990,
        5.088805,
        5.162828,
        8.415835,
        6.134088,
        5.509314,
        5.559452,
        6.459589,
        5.306280,
        4.551795,
        6.574756,
        4.976344,
        5.984862,
        5.064051,
        7.102298,
    ]
)
X = pd.DataFrame(X)

In [115]:
member = np.array(range(X.shape[0]))
# member[1] = 0
alpha = 1

In [116]:
u = np.sort(np.unique(member))  # unique array of cluster labels
N = len(u)  # number of clusters

for i in range(N):  # relabel clusters to be consecutive numbers (when user specified)
    member[np.where(member == u[i])[0]] = i

# sizes = np.zeros(2*N) #FIXME: append to this list
sizes = [sum(member == i) for i in range(N)]  # calculate initial cluster sizes

# array of within distances

In [151]:
def get_within(X, alpha):
    n = X.shape[0]
    return list(
        sum(
            np.power(
                np.sqrt(
                    sum(
                        (
                            X.iloc[
                                i,
                            ]
                            - X.iloc[
                                j,
                            ]
                        )
                        * (
                            X.iloc[
                                i,
                            ]
                            - X.iloc[
                                j,
                            ]
                        )
                    )
                ),
                alpha,
            )
            for j in range(n)
        )
        / (n**2)
        for i in range(n)
    )


within = [
    get_within(
        X.loc[
            [
                i,
            ]
        ],
        alpha,
    )[0]
    for i in range(N)
]

In [152]:
def get_between(X, Y, alpha):
    n = X.shape[0]
    m = X.shape[0]
    return list(
        sum(
            np.power(
                np.sqrt(
                    sum(
                        (
                            X.iloc[
                                i,
                            ]
                            - Y.iloc[
                                j,
                            ]
                        )
                        * (
                            X.iloc[
                                i,
                            ]
                            - Y.iloc[
                                j,
                            ]
                        )
                    )
                ),
                alpha,
            )
            for j in range(m)
        )
        / (m * n)
        for i in range(n)
    )

In [162]:
D = pd.DataFrame(index=range(N), columns=range(N))

for i in range(N):
    for j in range(N):
        between = get_between(
            X.loc[
                [
                    i,
                ]
            ],
            X.loc[
                [
                    j,
                ]
            ],
            alpha,
        )[0]
        D.iloc[i, j] = D.iloc[j, i] = 2 * between - within[i] - within[j]

In [181]:
D.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,0.0,2.96899,4.583014,2.277264,3.272382,3.426244,1.264652,1.320868,1.285228,0.634056,...,25.43276,25.533036,27.33331,25.026692,23.517722,27.563644,24.36682,26.383856,24.542234,28.618728
1,2.96899,0.0,1.614024,5.246254,0.303392,0.457254,1.704338,1.648122,1.683762,2.334934,...,22.46377,22.564046,24.36432,22.057702,20.548732,24.594654,21.39783,23.414866,21.573244,25.649738
2,4.583014,1.614024,0.0,6.860278,1.310632,1.15677,3.318362,3.262146,3.297786,3.948958,...,20.849746,20.950022,22.750296,20.443678,18.934708,22.98063,19.783806,21.800842,19.95922,24.035714
3,2.277264,5.246254,6.860278,0.0,5.549646,5.703508,3.541916,3.598132,3.562492,2.91132,...,27.710024,27.8103,29.610574,27.303956,25.794986,29.840908,26.644084,28.66112,26.819498,30.895992
4,3.272382,0.303392,1.310632,5.549646,0.0,0.153862,2.00773,1.951514,1.987154,2.638326,...,22.160378,22.260654,24.060928,21.75431,20.24534,24.291262,21.094438,23.111474,21.269852,25.346346

In [179]:
from scipy.stats import energy_distance

energy_distance([-7.207066], [-5.722571]) ** 2

2.96899

In [180]:
energy_distance([-7.207066], [-4.915559]) ** 2

4.583014